### ISSUE TITLE
Investigate Memory / Go routine leaks seen with v1.4.1 

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1001]
Related:
>  the Cloudflare testnet node node hit its 5Gb memory limit. Normal operating memory usage for nodes on our internal network (running 1.4.1-testnet) is steady at about 35Mb, but memory usage for the testnet node that’s also running the testnet-unchained-3s beacon is steadily increasing. It seems that there’s a memory leak somewhere in the unchained randomness sync logic? Note that this node is stuck at round 6710 still for that chain due to issues with the sync manager that are already known.

Memory leak:
![image](https://user-images.githubusercontent.com/10077203/167668659-d26b29be-767b-4d0c-a877-f068ae180f4e.png)

Go routines:
![image](https://user-images.githubusercontent.com/10077203/167668463-00879483-0650-482a-84ea-149fce1aba5b.png)

**Comment by CluEleSsUK** [comment]
We've identified and fixed a bunch of memory leaks over the past 2 years; if there are more, we can raise a detailed ticket around it
