### ISSUE TITLE
Give the LoE access to the Ceremony Dashboard

### ISSUE THREAD

**Issue by mcamou** [drand/drand#1012]
We would like the LoE to be able to access the Ceremony Dashboard. One idea is to create a Grafana Cloud user for them and share the user/password with them.

Once that is done, we can move the Ceremony Dashboard to its own folder, and grant the user access only to it. This also involves REVOKING access to that user to all other folders (since ATM they are all open).

Another option to explore (I'm not sure whether it can be done, I've seen it done with PowerBI) might be to have a different (open) website that uses some authentication token to embed the Grafana dashboard, and make that website totally public.

Other options are welcome.

**Comment by mcamou** [comment]
For the moment I've created a `drandloe` Grafana user (the password is in the  `Infra team` 1Password vault) and moved the dashboard to its own folder called `drand - LoE Public`.

**Comment by mcamou** [comment]
From [Grafana Community Support](https://community.grafana.com/t/grafana-cloud-embed-live-dashboard/40811): it seems that you can publicly share dashboards by opening a support case. I will explore that option.

**Comment by mcamou** [comment]
Actually... making it public might not be such a good idea. The main issue is that the dashboard is making multiple InfluxDB queries each time it refreshes (1+ per pane). If many people open it and/or set a very short refresh rate, it might affect our InfluxDB resource consumption. Ideally we would have some way of controlling access.

**Comment by mcamou** [comment]
I'm not sure how much work it would be to do a read-only, static copy, since it uses a lot of JS to get the metrics. Perhaps with something like Puppeteer...

**Comment by CluEleSsUK** [comment]
Closing this as we've totally moved dashboarding, and have plans to create separate public dashboards
