### ISSUE TITLE
Refactor: properly use int64 instead of int for the Rounds

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1015]
There are some places in the code where we iterate on round numbers using a int and cast it to a round number (int64).

This should be fine for the next 68 years, assuming somebody spins up a 1 second frequency network, but isn't sustainable behind that.
This could become more of an issue if we ever go below the 1s frequency.

Consider refactoring this properly and adding some unit tests around int32 vs int64.

**Comment by CluEleSsUK** [comment]
there are only two places we continue to use int rather than uint64, and both of them cast to uint64 - in principle this may fail on 32bit architectures in 68 years... but that's a risk I'm willing to take
