### ISSUE TITLE
Consider passing the `exhaustruct` linter

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1022]
This is a new linter that was introduced in 1.46 and it's currently showing ~300+ issues in our codebase. 

_Originally posted by @AnomalRoil in https://github.com/drand/drand/pull/1005#discussion_r891531158_

**Comment by CluEleSsUK** [comment]
I tried running this for science. Still reports a shitload of stuff, but there are so many false positives that integrating it would be painful. Closing for now.
