### ISSUE TITLE
Study if, why and when the Period is wrongly 0 in SyncManager during tests

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1023]
It seems we sometimes have a period of 0 in the SyncManager in tests, which probably means we're not always initializing our daemon properly in our tests.

It is used here: https://github.com/drand/drand/blob/f9a81de6e7e2fc22e7408677596da3343cfd8f1d/chain/beacon/sync_manager.go#L137
where it can cause issues.

Note that depending on the resolution of #1020 we might not need the Period in there at all.

It is set here:
https://github.com/drand/drand/blob/f9a81de6e7e2fc22e7408677596da3343cfd8f1d/chain/beacon/sync_manager.go#L71
and relies on the passed `*chain.Info` from the `SyncConfig`.

Todo:
- try to reproduce a case where it's 0
- if so, investigate
- otherwise close this.

**Comment by CluEleSsUK** [comment]
This doesn't seem to be the case anymore
