### ISSUE TITLE
Possible clashes between TLS settings in groupfiles

### ISSUE THREAD

**Issue by mcamou** [drand/drand#1036]
As part of debugging the DEDIS connectivity issues (see [this Slack thread](https://drandworkspace.slack.com/archives/C017YC40YAU/p1659008444491649)), we found the following:

* `pl2-rpc.testnet` can connect to the `drand.dedis.ch:4443` with no problem
* `pl1-rpc.testnet` cannot connect
* `pl2-rpc.testnet` is correctly using SSL to connect, while `pl1-rpc.testnet` is not
* The groupfile for the `testnet-unchained-3s` beacon in both hosts has `TLS = false`
* `pl2-rpc.testnet` also contains the `test-dedis` beacon, which has `TLS = true`

So, as part of the DEDIS connectivity test, the `test-dedis` beacon was set up and somehow it ended up with `TLS = true`. The fact that the `testnet-unchainded-3s` beacon was later set up with a conflicting `TLS = false` did not affect that.  

We should:

* Ensure that host-wide settings (e.g. `TLS`) are either in their own file, or set up equally in all beacons' groupfiles
* Figure out why `TLS = false` was set in the `testnet-unchained-3s` beacon

As an additional data point, DEDIS is using Nginx for TLS termination, so the drand daemon itself is run with `--tls-disable`. I have asked [in Slack](https://drandworkspace.slack.com/archives/C017YC40YAU/p1659009597697199) whether anyone remembers whether the `test-dedis` beacon was set up with this configuration, or whether drand was directly exposed without Nginx in the middle.

**Comment by mcamou** [comment]
From @willscott on Slack:
we don’t have config at the node level though, so would have to add that. it’s a remnant of how the zondax work happened for multi-beacon

**Comment by mcamou** [comment]
From @AnomalRoil on Slack:
Refactoring the way we handle TLS and its configuration might be a good idea anyway and shouldn't take too long in case we want to roll that in the next testnet ceremony.

**Comment by mcamou** [comment]
From @mcamou on Slack:
There are 2 places to fix this:

1. On the listener side. For this I think we still want the --tls-disable flag (for the reasons Nikolas mentioned above)
2. On the client side. For this I think we should always default to TLS=true but allow an escape hatch for testing or deploying on a local network (or perhaps even a flag to not check certificates, so you could deploy with a self-signed cert - not sure if that's already the case)

In any case, using TLS or not should be a host-wide configuration, not per-beacon, and I agree that it should not be tied to the host's ID.

**Comment by mcamou** [comment]
I changed the groupfile to `TLS = true` on `pl1`, and it fixed the current issue with DEDIS

**Comment by AnomalRoil** [comment]
Good, it confirms the issue really is the way we handle TLS.

**Comment by CluEleSsUK** [comment]
TLS is dead - long live TLS
