### ISSUE TITLE
Installation - make Error 1: go: updates to go.mod needed, disabled by -mod=readonly

### ISSUE THREAD

**Issue by nealmcb** [drand/drand#1039]
I followed the installation directions at [drand\-client CLI \| Drand \- Distributed Randomness Beacon\.](https://drand.love/developer/drand-client/) and got this, which I don't understand. I'm not really literate in the Go world....
This is on Ubuntu 20.04

```
$ cd drand
$ make drand-client
....
go: extracting github.com/klauspost/compress v1.15.1
go: updates to go.mod needed, disabled by -mod=readonly
make: *** [Makefile:83: client] Error 1

$ go version
go version go1.13.8 linux/amd64
```

Can someone decipher this for me and suggest how I can forward?

**Comment by AnomalRoil** [comment]
Seems to be working now (we require Go 1.19)
