### ISSUE TITLE
Avoid table scan for Len() call on BoltDB

### ISSUE THREAD

**Issue by CluEleSsUK** [drand/drand#1086]
An issue with slow remote status calls was resolved by skipping the `Len()` call on the Bolt DB store (see: https://github.com/drand/drand/pull/1085).

The `Len()` call is used in other places such as: https://github.com/drand/drand/pull/1084#discussion_r1016310766_

and should thus be refactored to not scan the entire table, as with millions of beacons this is super slow.
Presently, heuristics such as the current round number are an effective way to count the number of beacons, but if we implement beacon store trimming (https://github.com/drand/drand/issues/1053), this will no longer be an effective heuristic

**Comment by AnomalRoil** [comment]
Good find. This is probably why "resync works on my machine but not on testnet"

**Comment by CluEleSsUK** [comment]
we no longer use this Len(), so closing the issue. We could consider removing it from the interface in future
