### ISSUE TITLE
Investigate race condition in tests due to receiver on Handler.TransitionNewGroup being nil

### ISSUE THREAD

**Issue by dlsniper** [drand/drand#1112]
Without the nil check in `Handler.TransitionNewGroup`:
```
if h == nil {
```
some tests might fail with a race condition/panic due to `h` being nil.

See https://github.com/drand/drand/pull/1088#discussion_r1022521028

**Comment by CluEleSsUK** [comment]
In fact, the handler can be nil entirely in some circumstances! I stumbled across such issues during the DKG refactor (particularly when the tests run cleanup)

**Comment by CluEleSsUK** [comment]
In fact, the handler can be nil entirely in some circumstances! I stumbled across such issues during the DKG refactor (particularly when the tests run cleanup)

**Comment by CluEleSsUK** [comment]
this check is still there, though I'm not seeing the error anymore in tests and things were heavily refactored. Closing and will reopen if we ever see it again
