### ISSUE TITLE
Investigate why sometimes tests fail with pq: the database system is shutting down

### ISSUE THREAD

**Issue by dlsniper** [drand/drand#1127]
Sometimes, tests fail due to the database being still in use, see below.
This means some goroutine is not properly flagging the shutdown signal and does not propagate the context cancel correctly.
For an example, see [the following action](https://github.com/ardanlabs/drand/actions/runs/3952594540/jobs/6767871230#step:6:350).
Note that we know this to be loose goroutine as the test which it belongs to has finished before the message was printed.

```json
{
  "level": "FATAL",
  "ts": "2023-01-18T20:19:42.234Z",
  "logger": "BeaconTest.127.0.0.1:39413.2",
  "caller": "beacon/chain.go:122",
  "msg": "",
  "testName": "TestProcessingPartialBeaconWithNonExistentIndexDoesntSegfault",
  "chain_aggregator": "loading",
  "last_beacon": "pq: the database system is shutting down"
}
```

**Comment by CluEleSsUK** [comment]
not seen this post-v2
