### ISSUE TITLE
Drop all *Beacon references and use the values instead

### ISSUE THREAD

**Issue by dlsniper** [drand/drand#1132]
When using a beacon in the codebase, it should be done via value rather than pointers.
Similarly, when a pointer is created, the `Signature` and `PreviousSig` fields should be assigned via `copy()` rather than passing the slice to prevent any possible usage issues.
For MemDB, the storage backend should stop using `[]*chain.Beacon` and use only `[]chain.Beacon`.

Note: this is a breaking change for any exposed Go API and should be part of a new major version release.

**Comment by CluEleSsUK** [comment]
This no longer exists in the main codebase for v2
