### ISSUE TITLE
Investigate error handling in beaconCache

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1135]
Should these errors be ignored?

	id := roundID(p.GetRound(), p.GetPreviousSignature())
	idx, _ := c.scheme.ThresholdScheme.IndexOf(p.GetPartialSig())

https://github.com/drand/drand/pull/1103#discussion_r1088009704

	idx, _ := c.scheme.ThresholdScheme.IndexOf(p.GetPartialSig())

https://github.com/drand/drand/pull/1103#discussion_r1088009954

**Comment by CluEleSsUK** [comment]
this could actually cause a panic - may well be worth fixing
