### ISSUE TITLE
Investigate error handling in node.go

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1136]
idx, _ := key.Scheme.IndexOf(p.GetPartialSig())
	idx, _ := h.crypto.ThresholdScheme.IndexOf(p.GetPartialSig())

Should the error here be ignored?

https://github.com/drand/drand/pull/1103#discussion_r1088012283

And also in node_test.go:
https://github.com/drand/drand/pull/1103#discussion_r1088014229

**Comment by CluEleSsUK** [comment]
this only exists in the demo test now, so I think we're safe to close
