### ISSUE TITLE
Add mutex to guard Verifying client log

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1138]
It seems we potentially have a race here if people are changing the logs too often for their verifying client. This is currently only used in our constructors without concurrency, so should be fine for now.

```
func (v *verifyingClient) SetLog(l log.Logger) {
	v.log = l.Named("verifyingClient")
```

A better alternative might be to just set it once in the constructor.

To do:
- [ ] investigate
- [ ] refactor

**Comment by CluEleSsUK** [comment]
This has been extracted with the CLI
