### ISSUE TITLE
increase partial beacon cache limit

### ISSUE THREAD

**Issue by CluEleSsUK** [drand/drand#1153]
Currently the partial cache is limited to 100 beacons.
If nodes get very far behind (for example, in a network outage), the start to drop partial beacons for nodes that are ahead which could be slowing down network recovery in disaster scenarios.

**Comment by nikkolasg** [comment]
The partial cache is limited to 100 partial beacons _per node_ [here](https://github.com/drand/drand/blob/master/chain/beacon/cache.go#L94). The numbers of _rounds_ "in progress" actually can be infinite (and probably should not be).

**Comment by CluEleSsUK** [comment]
Aha noted - thanks for pointing this out, I hadn’t noticed!

Right now we‘re seeing a lag of 15000+ beacons in testnet and thus all kinds of  behaviours (and code paths) we haven’t witnessed up to now. I’d love to test some more disaster scenarios to see how all our channels/timeouts/sync/catch-up procedures behave
