### ISSUE TITLE
Update readme for new instructions to fetch package with go module

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#117]
Drand uses now go modules but the readme instructions are not updated. I think people should be using `GO111MODULE=on go get ...` otherwise we run into issues like #116 .

**Comment by AnomalRoil** [comment]
Also we might want to check that the docker stuff is still working now with Go modules?

**Comment by nikkolasg** [comment]
drand now uses go modules by default, and with go1.14 i think it's by default
