### ISSUE TITLE
Race condition in urfave/cli newer than v2.20.1

### ISSUE THREAD

**Issue by dlsniper** [drand/drand#1171]
Tracked in: https://github.com/urfave/cli/issues/1699

Upgrading to a more recent version of [urfave/cli](https://github.com/urfave/cli/) will produce a race condition due to global variables in the package itself.

The race condition is not related to Drand itself and can be reproduced with the following code, see below.

As such, the library should not be upgraded past `v2.19.2`  to avoid any such problems.

At the time of writing, version v3.0.0-alpha2 does not allow us to upgrade past v2.20.1.

```go
package main

import (
	"time"

	"github.com/urfave/cli/v3"
)

var demoFlag = &cli.StringFlag{
	Name:    "demo",
	Value:   "demo",
	Usage:   "demo",
	EnvVars: []string{"RACE_DEMO"},
}

var appCommands = []*cli.Command{
	{
		Name:  "race",
		Usage: "Start the demo",
		Flags: []cli.Flag{demoFlag},
		Action: func(c *cli.Context) error {
			return cmd1(c)
		},
	},
}

func cmd1(_ *cli.Context) error {
	time.Sleep(1 * time.Second)
	return nil
}

func newApp() *cli.App {
	app := cli.App{
		Name:            "demo",
		HideHelpCommand: true,
		HideVersion:     true,
		HideHelp:        true,
		Commands:        appCommands,
	}
	return &app
}

func main() {
	go func() {
		startArgs := []string{
			"demo",
			"race",
		}
		err := newApp().Run(startArgs)
		if err != nil {
			panic(err)
		}
	}()

	var err error

	for i := 0; i < 3; i++ {
		startArgs := []string{
			"demo",
			"race",
		}
		err = newApp().Run(startArgs)
		if err == nil {
			return
		}
		time.Sleep(500 * time.Millisecond)
	}
	if err != nil {
		panic(err)
	}
}
```

**Comment by AnomalRoil** [comment]
While the above code still crashes `urfave/cli` using their latest `v2`, it seems it doesn't trigger races in our tests anymore.

I think we can just upgrade it now.
