### ISSUE TITLE
Improve Randomness Extraction

### ISSUE THREAD

**Issue by chgorman** [drand/drand#1183]
[Randomness extraction](https://github.com/drand/drand/blob/master/crypto/schemes.go#L245-L252) currently uses a hash function to extract randomness from the signature. Because a signature may be treated as nonuniformly random bytes, some method of processing is required to obtain uniformly random bytes. Key Derivation Functions are designed to convert nonuniform randomness into uniform randomness. Thus, it would be better to replace the call to a hash function to a call to HKDF.

Details on HKDF may be found in the [RFC](https://www.rfc-editor.org/rfc/rfc5869) or [paper](https://eprint.iacr.org/2010/264.pdf).

**Comment by CluEleSsUK** [comment]
We may implement this in https://github.com/randa-mu/drand-cli in future, but not here, so closing for now
