### ISSUE TITLE
membd backend sync from 0 when the network is in catchup

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#1192]
Currently if a network is in catchup mode, when a `memdb` node starts the `memdb` storage backend will start syncing from 0 instead of getting the latest round from the other nodes and starting to catchup with the rest of the network from there.

Expected behaviour:
- the memdb backend should try to fetch the latest round from its peers, even when the network is in catchup mode, instead of syncing from 0.

**Comment by dlsniper** [comment]
Fixed in #1193
