### ISSUE TITLE
Whether Drand runs on an asynchronous network

### ISSUE THREAD

**Issue by kase113** [drand/drand#1219]
I'd like to be able to use Drand as a random beacon on an asynchronous network, but I don't see a description of that

**Comment by CluEleSsUK** [comment]
Hi @kase113 - could you give a little more detail on your use case? Do you mean consuming randomness via e.g. websockets rather than REST?

**Comment by AnomalRoil** [comment]
drand's DKG is assuming a synchronous network currently. We are investigating switching to an asynchronous one, but the research on that topic is still relatively fresh.
