### ISSUE TITLE
DKG timing & access

### ISSUE THREAD

**Issue by burdges** [drand/drand#1320]
How far in advance do the preliminary DKG rounds run?

Is there public access to commitments from those DKG rounds?

**Comment by AnomalRoil** [comment]
The transition time is something that's configurable, but it typically happens to within a few minutes of the DKG, so not too many rounds. 

We aren't currently recording and publishing our DKG transcripts, but we could if there's any interest or need to, in order to help supporting more usage

**Comment by AnomalRoil** [comment]
Yup, timelock is live. We got a Go library and CLI and a JS library for it as well as a demo webapp to play with it: https://timevault.drand.love/
