### ISSUE TITLE
Add documentation from external user point of view: API and libraries

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#133]

**Comment by nikkolasg** [comment]
Doc in progress at : https://hackmd.io/s/HJ9lg5ZTE

**Comment by nealmcb** [comment]
Add an example of fetching a specific round, e.g.

     https://drand.cloudflare.com/api/public?round=59705

and point to the code that specifies that - perhaps https://github.com/dedis/drand/blob/master/protobuf/drand/public.proto
