### ISSUE TITLE
race occasionally detected during shutdown of tests

### ISSUE THREAD

**Issue by CluEleSsUK** [drand/drand#1347]
A race is detected between the daemon's `Stop` method and the `FanOutChannel`'s `Chan` function being used in the DKG `Process`, as we only check the results of the leader's DKG in a bunch of tests.

We should ensure all of them shut down gracefully to avoid the flaky test.

**Comment by AnomalRoil** [comment]
This was a missed attempt at fixing it: b88035d41724b2e1f5dff573d4288e22bf39cee7
