### ISSUE TITLE
no cert.pem

### ISSUE THREAD

**Issue by zhouzhou84** [drand/drand#135]
At first, it shows that` cert.pem no such file`

the it shows that `Error: No such container: node5`

**Comment by nikkolasg** [comment]
Hi. Could you be more descriptive please ?

Depending on your setup, you might need to run the test script `run_local.sh` with sudo.

**Comment by zhouzhou84** [comment]
> @zhouzhou84 did you solve the problem ? If yes I will close the issue and if not, feel free to give more details so that we can help.

ok, if I miss it again, I will come here ,thank you so much
