### ISSUE TITLE
Where did the client libraries go in the v2 branch?

### ISSUE THREAD

**Issue by advdv** [drand/drand#1377]
Sorry, I must be asking something obvious but I cannot seem to find the Go client code in the v2 branch. Specifically the HTTP client as described here: https://pkg.go.dev/github.com/drand/drand/client/http

It seems the v2 branch only holds the server code? I could be wrong but I can't find any changelog or issue that describes this change. I through maybe it moved to another repo but I can't seem to find it either.

**Comment by CluEleSsUK** [comment]
here it is: https://github.com/drand/go-clients

**Comment by AnomalRoil** [comment]
Please @advdv wait maybe for the `v1.0.0` release of the said client, the API might still change in the next few weeks.

**Comment by advdv** [comment]
sure, no problem. Thanks for the headsup!
