### ISSUE TITLE
how to incorporate new entropy during a reshare

### ISSUE THREAD

**Issue by jeffallen** [drand/drand#149]
I was looking to understand how Univ Chile incorporates entropy into reshares, and I cannot see anything in the docs or the code that allows this.

How do they do it? How should other drand users do it?

**Comment by nikkolasg** [comment]
So the code supports it but there's not a clear way on how to do it yet for any kind of external entropy.
I'm thinking of implementing a simple command line flag that takes a command to run to get the entropy.
This command should return a random hexadecimal string so drand would parse it and use it internally.

**Comment by nikkolasg** [comment]
the drand CLI now supports a flag that takes in a script that returns randomness when called that is fed into the DKG library.
