### ISSUE TITLE
Extraneous non-JSON duplicate text emitted when retrieving public beacon

### ISSUE THREAD

**Issue by grempe** [drand/drand#152]
Following the install/use instructions on the new League of Entropy page there is some duplicate text output.

https://www.cloudflare.com/leagueofentropy/

This text should probably be removed, as it is both displayed in duplicate and it would prevent parsing the output of this command with a JSON parser like `jq`.

Duplicate text `group file loaded with 8 participantsgroup file loaded with 8 participants`

```
$ ./drand get public deploy/190604/group.toml
group file loaded with 8 participantsgroup file loaded with 8 participants{
    "round": 19008,
    "previous": "2d5a7869a3f08c7c0f00b03d0dc4a5320415de375ed17934b2ddca784907cae72e784f93c74dc2d427f5f71b9e6748f259acb059d9d11f4b0b6f7810c3d5cced",
    "randomness": {
        "gid": 21,
        "point": "505e90af8abd9713c6fa2a9fc0ed04ebe2ea2228498fdca43df67fa39db555060723049825ac0594b311dea5bca2199dde01bda8a773680b61ce30b2625dd224"
    }
}%
```

**Comment by Snawoot** [comment]
Probably it can be resolved if daemon would output its messages into stderr and JSON into stdout. I think current fix in #154 doesn't resolves issue completely.
