### ISSUE TITLE
Proposed (smaller) Dockerfile

### ISSUE THREAD

**Issue by DazWilkin** [drand/drand#155]
The current Dockerfile generates an image of 442MB.

```bash
docker image ls --format="{{.Repository}}\t{{.Tag}}\t{{.Size}}"
drand  before  442MB
```
Using Google [DIstroless](https://github.com/GoogleContainerTools/distroless) and a multi-stage build reduces the image size to 35.3MB
```bash
docker image ls --format="{{.Repository}}\t{{.Tag}}\t{{.Size}}"
drand  after   35.3MB
drand  before  442MB
```
Only the `drand` binary is copied to the runtime image. There's no need to remove the sources in the first stage because these aren't included in the runtime image. Reordering the `WORKDIR` and `COPY` commands simplifies things too.

```Dockerfile
FROM golang:1.12.4 as build

MAINTAINER Nicolas GAILLY <nikkolasg@gmail.com>

RUN apt-get update && \
    apt-get install -y  bash git openssh-server && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/dedis/drand

COPY . .

ENV GO111MODULE=on

RUN go install -mod=vendor


FROM gcr.io/distroless/base

COPY --from=build /go/bin/drand /

ENTRYPOINT ["/drand"]
```
Appears to work but needs appropriate testing:
```bash
docker build --tag=drand:after --file=Dockerfile .
docker run --interactive --tty drand:after
NAME:
   drand - distributed randomness service
USAGE:
   drand [global options] command [command options] [arguments...]
```

**Comment by nikkolasg** [comment]
That is awesome!  Since you've went to the trouble of even writing down the Dockerfile, do you think you could make a PR for this ?

**Comment by DazWilkin** [comment]
Sure!

**Comment by nikkolasg** [comment]
Fixed  in https://github.com/drand/drand/pull/241
