### ISSUE TITLE
generate-keypair could use an --output-folder parameter for simplicity

### ISSUE THREAD

**Issue by lbarman** [drand/drand#159]
It's a bit cumbersome that `drand generate-keypair` always output keys in `~/.drand` *and* refuses to output new keys if some already exist.

We could simplify the setup (and the docker guides) if there was an `--output-folder` flag.

**Comment by nikkolasg** [comment]
There is already the flag `--config` which specifies where to put the keys , group and beacon database. I chose to only have one folder for ease of use and implementation. Would that work for your use case or do you need finer granularity (and if yes, why ? ) ?

**Comment by lbarman** [comment]
Ah, perhaps I missed it.

I wanted to simplify https://github.com/dedis/drand/blob/infra-overhaul/deploy-example/README_docker.md section "Generate drand keys", to avoid the `mv` and also so that the generation does not fail if you already have keys.

It's a minor enhancement indeed.

**Comment by nikkolasg** [comment]
Can you change the docker so it uses the `--config` flag so you dont need the `mv` anymore ?
And for "not failing if there are already keys", one thing that could be possible is to have a `--force` flag for example, that overrides the keys if present. I just dont want to have the possibliity to overwrite private keys *by default*.

**Comment by lbarman** [comment]
Sounds good !
I don't have time to do it right now, if that's fine, let's keep this open and I'll address it at some point (or if someone wants to do a PR it's very welcome).

**Comment by nikkolasg** [comment]
Closing for now since I think the CLI already provides what we need to solve this if it is still a problem.
