### ISSUE TITLE
Are the signatures (points) actually random? Why?

### ISSUE THREAD

**Issue by nealmcb** [drand/drand#165]
I'm confused by the documentation at https://hackmd.io/@nikkolasg/HJ9lg5ZTE

> Here randomness is the latest random value, which is a threshold BLS signature of the previous random value Previous and the round number. The field Round specifies the index of Randomness in the sequence of all random values produced by this drand instance. The message signed is the concatenation of the round number treated as a uint64 and the previous randomness. The gid is an indicator of the group this point belongs to. At the moment, we are only using BLS signatures on the bn256 curve and the signature is made over G1.

I'm  unclear on exactly what it is describing as random here, and why. Despite the text, the "randomness" structure as a whole obviously isn't since `gid` is always 21 now.  The other value, `point`, is described as a "BLS signature". I'm not used to signatures being random, but from the context it seems you're saying it is. I dare say that some of the other technical documentation is relevant, but it is also not clear to the user or a layman.

Could you be explicit about that, and point to documentation on why it can be assumed to be uniformly distributed and unpredictable? Maybe even use a name more obvious than "point"?
Maybe document somewhere how many bits you're providing (512 I guess based on 128 4-bit hex digits)?

Note also that [the main README](https://github.com/dedis/drand/blob/master/README.md) still says

> NOTE: At the moment, the REST endpoints return base-64 encoded values, whereas the drand cli tool returns hexadecimal encoded value (issue).

though the referenced issue has been closed: https://github.com/dedis/drand/issues/85 

I just proposed a PR to remove that: https://github.com/dedis/drand/pull/164

**Comment by nikkolasg** [comment]
Hi @nealmcb , thanks for your suggestions.

drand's output contains the signature which is uniformly distributed in the "signature space" . drand next release will hash this signature to get a completely uniform byte level representation (a BLS signature can easily be detected as such since it is constrained by the algebrae of the curve).
I will include more details in the doc about that and the output based on your suggestions.

Thanks for the PR !

**Comment by nikkolasg** [comment]
More info on that here now: https://hackmd.io/hALYmUf1TTCJVIxECIkgYw?view#Chained-Randomness
