### ISSUE TITLE
"get public" instructions don't work

### ISSUE THREAD

**Issue by jeffallen** [drand/drand#186]
At Cloudflare, https://www.cloudflare.com/leagueofentropy/

There are instructions that say:
```
go get -u github.com/dedis/drand 
cd $GOPATH/src/github.com/dedis/drand 
go build 
./drand get public deploy/190604/group.toml
```

Even adjusted for the new repo location, they don't work with 487c0ce8dddde29678e8b7d850ee95132a669cc2:

```
$ ./drand get public deploy/190604/group.toml 
drand: error loading group file: [group: unwrapping node[0]: compression flag should be set]
```

**Comment by nikkolasg** [comment]
Instructions are outdated from master - readme instructs to follow the web/ branch. Things will work out of master for next setup.
