### ISSUE TITLE
Curve used: BN256 or BLS12-381?

### ISSUE THREAD

**Issue by sbellem** [drand/drand#200]
From inspecting the code, it looks like BLS12-381 is used ... https://github.com/drand/drand/blob/c1195953f8a3d9fd252d444349a8c8a7a79d8e31/key/curve.go#L12
https://github.com/drand/drand/blob/c1195953f8a3d9fd252d444349a8c8a7a79d8e31/key/curve.go#L30

and the post https://hackmd.io/@nikkolasg/HyUAgm234 mentions:

> drand currently uses the BLS12-381 curve

However, the `README` mentions that:

> At the moment, we are only using BLS signatures on the BN256 curves and the signature is made over G1.

Just wish to clarify ... :smile:

**Comment by nikkolasg** [comment]
Sorry you come at a wrong moment where I'm transitioning drand code and a new network will emerge using BLS12-381. 
Thanks for spotting that up, I'll change it in the README.

**Comment by sbellem** [comment]
> Sorry you come at a wrong moment where I'm transitioning drand code and a new network will emerge using BLS12-381.
> Thanks for spotting that up, I'll change it in the README.

No problem! After looking at the code and also the `drandjs` code it became clear that BLS12-381 is used!

**Comment by nikkolasg** [comment]
Updated in readme and will write a more detailed spec :)
