### ISSUE TITLE
Document current algorithm used for hashing the message to G2

### ISSUE THREAD

**Issue by sbellem** [drand/drand#203]
_draft_

The current (`master`) code appears to use the MapToGroup or [try-and-increment](https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-00#appendix-A) approach (from [[BLS01]](https://iacr.org/archive/asiacrypt2001/22480516.pdf)) to find a valid point on the curve.

It would be very useful to document which algorithm is used for people who wish to use a different programming language to verify signatures.

On a related note, it may also be useful to document the roadmap with respect to which algorithm will be eventually in use.

Different implementation of BLS signatures are following https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-05.

**Comment by nikkolasg** [comment]
Drand now uses the curve BLS12-381 with public keys on G1 with the hash to curve v7 https://tools.ietf.org/html/draft-irtf-cfrg-hash-to-curve-07 .
There's a plan to write a fully detailled spec that will contain these information.
