### ISSUE TITLE
nginx config example: `location /api/ or /api`

### ISSUE THREAD

**Issue by sbellem** [drand/drand#209]
The example configs at https://github.com/drand/drand#tls-setup-nginx-with-lets-encrypt and https://hackmd.io/@nikkolasg/Hkz2XFWa4#TLS-setup-Nginx-with-Let%E2%80%99s-Encrypt contain:

```conf
server {
  # ...
  # JSON REST endpoints, converted from gRPC
  location /api/ {
      # ...
  }
}  
```

perhaps it is my specific configuration that is the problem, but I could not get that working as I would get a `301 Moved Permanently` or `Not Found` for sending requests to `https://<address>/api` and `https://<address>/api/` respectively. Removing the trailing slash, `/api/` --> `/api` worked. In the context of the above snippet:

```conf
server {
  # ...
  # JSON REST endpoints, converted from gRPC
  location /api {
      # ...
  }
}  
```

**Comment by nikkolasg** [comment]
Public api endpoint changed now - see [doc](https://github.com/drand/drand/blob/master/docs/DEPLOYMENT.md#tls-setup-nginx-with-lets-encrypt)
