### ISSUE TITLE
run_local.sh affects my network.

### ISSUE THREAD

**Issue by herumi** [drand/drand#22]
I assign 192.168.0.1 to the default gateway and nameserver.
```
>route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         192.168.0.1     0.0.0.0         UG    0      0        0 ens33
192.168.0.0     *               255.255.255.0   U     0      0        0 ens33
```
```
>cat /etc/resolv.conf
nameserver 192.168.0.1
```
After running `sudo ./run_local.sh`, the network interface br-XXX is assigned to 192.168.0.1 and can not resolve address.
```
>ping www.google.com
ping: unknown host www.google.com
```
If I remove the interface, then I can ping.
```
>docker network ls

NETWORK ID          NAME                DRIVER              SCOPE
63b20fcb86f8        drand               bridge              local

>docker network rm 63b20fcb86f8

>ping www.google.com
PING www.google.com (172.217.26.100) 56(84) bytes of data.
64 bytes from kix05s01-in-f4.1e100.net (172.217.26.100): icmp_seq=1 ttl=51 time=12.3 ms
```
Is this a correct specification?

**Comment by nikkolasg** [comment]
Sorry for the late reply. I re-wrote most of the drand code and have a cleaner version now. 
Although, I am still using the `run_local.sh` script to do the docker testing.
If you are willing to retry with the current code, and keep me updated on this if the error still occurs, I'd greatly appreciate !
(also, are you on MacOS?)

**Comment by nikkolasg** [comment]
Closing in the meantime
