### ISSUE TITLE
how to generate the same random value with anothe drand system

### ISSUE THREAD

**Issue by hunjixin** [drand/drand#234]

**Comment by nikkolasg** [comment]
Can you precise your question ? What do you want to achieve ?

From what I understand, if you want to achieve the same distributed public key for two different networks, you need to make sure nodes on both network use the same source of entropy, and you can give the source of entropy via the CLI and add `--user-only` . But please clarify.

**Comment by hunjixin** [comment]
@nikkolasg 
thansks for reply,

filecoin use drand to generate randness, but i want to deploy a local drand to generate the same  randness for more reliability.
  i want to confirm that drand can generate the same randness of corresponding round between local and official system if has the same boot paramesters.

**Comment by Daeinar** [comment]
Since drand basically implements a distributed PRF it is theoretically possible to reconstruct the whole stream on a local network. Practically that would mean, however, that you need the secret keys of all the nodes involved in the live network which is not feasible as you would be able to predict the output of the live network.

Why do you want to re-generate the drand randomness locally?

**Comment by hunjixin** [comment]
@Daeinar  
just  for avoiding external influence as much as possible in intranet.

i read the code just now，drand use h(sig) as rand, It means almost impossible to generate the same rand

**Comment by Daeinar** [comment]
Well if you had access to all the secret keys, then you could re-generate `sig` and therefore `h(sig)` which however would be against the purpose of drand. In any case if you are only worried about biasing attacks, then simply us drand's public key to verify `sig`, recompute `h(sig)` and check that the result is the same value as the one we deliver through the web API.

**Comment by hunjixin** [comment]
@Daeinar bls sig give the same result for the same value and secret key？

**Comment by Daeinar** [comment]
Yes they do. A [BLS signature](https://en.wikipedia.org/wiki/Boneh%E2%80%93Lynn%E2%80%93Shacham) is  computed as `sig = H(m)^x` where `m` is the message and `x` is the secret key. There is no additional randomness needed as, for example, in Schnorr signatures. 

drand produces a signature chain where the i-th signature is computed as `sig_i = H(i || sig_{i-1})^x` and the i-th randomness as `rnd_i = H(sig_i)`. So if you would know all the secret keys that are involved in the distributed signing process you could fully reconstruct the entire signature chain and all random values and even look at future values.

**Comment by hunjixin** [comment]
@Daeinar  got it. Thank you for your patience

**Comment by Daeinar** [comment]
@hunjixin You're welcome! 

Closing this issue.
