### ISSUE TITLE
Folder flag should not be a command and global flag

### ISSUE THREAD

**Issue by travisperson** [drand/drand#243]
The local flag shadows the global flags which results in confusion when a command doesn't do what a user might expect after setting the `--folder` flag on the global level.

**Comment by AnomalRoil** [comment]
Todo: 
https://github.com/drand/drand/blob/a2a22571f4d0b4c76587fa4bd4bda4c95d31a848/cmd/drand-cli/cli.go#L571-L572

**Comment by AnomalRoil** [comment]
The issue is when running:
```
drand --folder test start --folder test2 
```
`test2` is used and not `test`.

I guess the solution is to:
- [ ] remove the option to pass the folder flag as a global flag
