### ISSUE TITLE
Stabilize integration CI test

### ISSUE THREAD

**Issue by willscott** [drand/drand#244]
<img width="972" alt="Screen Shot 2020-05-04 at 1 10 56 PM" src="https://user-images.githubusercontent.com/428199/81009038-bc677200-8e08-11ea-9e14-c1c4e0f0f66e.png">

We need to figure out how to get the `test-integration` to pass more reliably.

**Comment by willscott** [comment]
it sounds like the issue is that the time period is too tight for circle when under load, and nodes are missing their deadlines
```
ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:317 index=3 level=error beacon_round=17 err_request="rpc error: code = Unknown desc = invalid round: 17 instead of 16" from=127.0.0.2:41323

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:317 index=3 level=error beacon_round=17 err_request="rpc error: code = Unknown desc = invalid round: 17 instead of 16" from=127.0.0.5:33099

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:317 index=3 level=error beacon_round=17 err_request="rpc error: code = Unknown desc = invalid round: 17 instead of 16" from=127.0.0.4:44711

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:317 index=3 level=error beacon_round=17 err_request="rpc error: code = Unknown desc = invalid round: 17 instead of 16" from=127.0.0.7:38191

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:317 index=3 level=error beacon_round=17 err_request="rpc error: code = Unknown desc = invalid round: 17 instead of 16" from=127.0.0.6:35477

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:317 index=3 level=error beacon_round=17 err_request="rpc error: code = Unknown desc = invalid round: 17 instead of 16" from=127.0.0.3:45201

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:317 index=3 level=error beacon_round=17 err_request="rpc error: code = Unknown desc = invalid round: 17 instead of 16" from=127.0.0.8:42965

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:112 index=3 level=debug received=request from=127.0.0.1:36462 round=17 prevround=16

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:118 index=3 level=error process_partial=127.0.0.1:36462 invalid_future_round=17 current_round=16

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:112 index=3 level=debug received=request from=127.0.0.1:36458 round=17 prevround=16

ts="Mon, 04 May 2020 19:45:18 UTC" call=handler.go:118 index=3 level=error process_partial=127.0.0.1:36458 invalid_future_round=17 current_round=16

ts="Mon, 04 May 2020 19:45:22 UTC" call=server_metrics.go:107 level=info public_rand=127.0.0.1:41466 round=16 reply="{ round: 16, sig: 855d01, prevSig: a15249 }"
```

**Comment by nikkolasg** [comment]
I think so too.
So there's a bunch of parameters we could tweak, I list them here in order of "impact" (so the first one are more likely to impact the success rate):
* [BeaconPeriod](https://github.com/drand/drand/blob/master/demo/main.go#L49): the frequency of the randomness generation. 10s might work much better.
* [Wait time](https://github.com/drand/drand/blob/master/demo/main.go#L36) before checking a randomenss: maybe all nodes didn't finish to process all partial signatures and reconstruct them in time when we check them - and the demo checks them randomly.
* [BeaconOffset](https://github.com/drand/drand/blob/master/demo/main.go#L30): From the time we run the resharing, we add this time to compute the unix timestamp where the new group will take over - the resharing doesn't halt the network, the new group takes over at a specified round -. If the load is too heavy, the resharing might take too long and some nodes couldn't finish the dkg in time and therefore couldn't have their partial share in time to participate to the next round in time.

**Comment by nikkolasg** [comment]
Bumpng it up again, new error appeared 
> ts="Wed, 06 May 2020 23:49:00 UTC" call=handler.go:148 index=4 level=error process_partial=127.0.0.1:43384 same_index=got 4=our 4=inadvance_packet?
