### ISSUE TITLE
Folder permission: warning or error ?

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#245]
From https://github.com/drand/drand/pull/242#pullrequestreview-405314601:
Before the code returned an error if the permission of the folder were not setup correctly. But it became very annoying on some setup, but now that we want to harden the setup of a node, it might be a good idea to set that back in order to make sure we don't expose the folder with too permissive permissions.

**Comment by willscott** [comment]
Do expect the producers to be running drand on machines / containers with multiple users? I suspect in practice a warning will be enough.

**Comment by nikkolasg** [comment]
Not necessarily real users but if there is a http server that is running alongside under another "unix user" ? (for example to answer client's request or else). 
I'm fine with saying a warning is enough, but in that case, is a warning required at all :D ?

**Comment by AnomalRoil** [comment]
Drand is now meant to be run in a closed environment, multiple users on the same machine should all be properly authorized and their action logged anyway.
