### ISSUE TITLE
High level Client API

### ISSUE THREAD

**Issue by willscott** [drand/drand#248]
Currently, clients making use of drand make a
[`net.NewGrpcClient()`](https://github.com/drand/drand/blob/master/net/client_grpc.go#L38)
or a
[`net.NewRestClient()`](https://github.com/drand/drand/blob/master/net/client_rest.go#L27)

These are abstracted by the `net.PublicClient` interface, with a wrapper 
[`core.Client()`](https://github.com/drand/drand/blob/master/core/client_public.go) wrapping these RPC layers with the client verification needed for local safety.

This Interface does not provide a few features that appear desirable to consumers, as we've seen in the custom client logic package implemented by [lotus](https://github.com/filecoin-project/lotus/blob/testnet/3/chain/beacon/drand/drand.go)

In particular, it looks like a client library for Drand should include
* Caching
* Creating a channel following new values, rather than requiring the consumer to poll for new values / figure out when new values will be released.
* Estimation of when the next value will be released.

In addition, we should provide a more codified interface for specifying the group key and servers/peers/bootstraps/how-to-connect, so that internal details like the network protocol can be updated in library releases without as much coordination with consumers.

**Comment by willscott** [comment]
cc @whyrusleeping / @kubuxu - Any other thoughts on constraints in your head for consuming randomness would be useful.

**Comment by nikkolasg** [comment]
Yes there is a mixin of functionalities between `net/` and `core/` for client that I have been meaning to tackle for a while. For example, `net/` already contains a higher level streaming API that returns a channel, but it should probably be in `core/`.

**Comment by nikkolasg** [comment]
> In addition, we should provide a more codified interface for specifying the group key and servers/peers/bootstraps/how-to-connect,

What do you have in mind exactly ?

**Comment by willscott** [comment]
> What do you have in mind exactly ?

I don't think i have a specific proposal yet, but if clients are either connecting over gossipsub, or if relaying happens through CDNs / web servers chosen by the publishing group, it would be useful to extend the client interface so that:
* Initial creation can occur from some opaque 'config' information generated by the publishers - e.g. bootstrap servers / URLs
* The interface probably ends up including hooks for updating / saving local state - things like active peers, additional server locations that have been rotated to, etc.

**Comment by nikkolasg** [comment]
I see - 
IMO the current group file should now be restricted to "drand nodes internally" only, and then we have a _public_ configuration file that contains public information as you mention.

**Comment by willscott** [comment]
Here's a first pass at an interface to a client package. It isn't too far off from the interface @whyrusleeping constructed in functionality:
```golang
package client

import (
	"context"
	"encoding"
)

// Client represents the drand Client interface.
type Client interface {
	// TextMarshaler (the 'MarshalText' method) allows serialization of the client
	// state for subsequent restoration. The marshalled value can be passed to `New`
	// to restore Client state.
	encoding.TextMarshaler

	// Get returns a the randomness at `round` or an error over a result channel.
	// One result will be returned, with exactly one of Err or Data populated.
	func Get(ctx context.Context, round uint64) <-chan Result

	// RoundAt will return the most recent round of randomness that will be available
	// at time for the current client.
	func RoundAt(time time.Time) uint64
}

// Result represents the randomness for a single drand round.
type Result struct {
	Err error
	Round uint64
	Data []byte
}

// New creates a new Client, or a non-nill error if the input state cannot be parsed.
func New(state []byte) (Client, error)
```

I'll put this in a pull request for discussion

**Comment by anorth** [comment]
You can consult [go-filecoin's DRAND client](https://github.com/filecoin-project/go-filecoin/tree/master/internal/pkg/drand) for reference too. (Currently has provisions for a prior protocol version where rounds were discontinuous, which will greatly simplify).

**Comment by Kubuxu** [comment]
A very useful mechanism would be enforcing that randomness is coming from a given group.
If you look at how it is done in lotus right now we construct a gRPC client, fetch group info and compare it with group info baked into our binary.

An important point is distribution network endpoints and group info might be different, for example when we fork to another drand deployment, so it needs to be passed from the side of library user.

**Comment by willscott** [comment]
As long as you bake the key into the binary, and the produced randomness is still validated by that key, my understanding is that the specific endpoints / group members can vary - in particular when resharing occurs.

**Comment by nikkolasg** [comment]
I'd say both point of view are correct and we need to find the balance:
* When we only do resharing, the distributed key will not change and you can verify any given beacon
* But _where_ to fetch that beacon might change. However, the distribution network will be completely orthogonal to the drand network itself soon so that shouldn't be something drand should care about.
* However, when a new drand network is created, how do we signal that, how do nodes get the new distributed public key, how does relay node know that etc... That's totally unclear now.

**Comment by willscott** [comment]
closing this issue as #251 is merged. This will continue to evolve, but i think the shape of constraints has gotten more clear.
