### ISSUE TITLE
Separate binaries for drand group members and consumer

### ISSUE THREAD

**Issue by willscott** [drand/drand#250]
The current `drand` binary does several things

* manages the daemon
* runs the offline DKG process
* runs the online daemon beacon process
* consumes/fetches public randomness from a drand group
* utilities for network diagnostics
* utilities for key generation

We should consider refactoring the security-critical tasks into single-purpose binaries without extraneous code / less potential for bugs to sneak in.

In particular, this issue can track the factoring out of the
* "online drand daemon"
* "drand client"

**Comment by nikkolasg** [comment]
Even though it's closed I want to say I disagree with splitting in multiple binaries; that just leads to higher overhead.
Look at docker: everything is doable from the same unique binary and it's quite useful.

**Comment by willscott** [comment]
We also can still do everything from the primary binary. I think it is nice to have the lighter weight client library dependency built separately so that we can validate that it is indeed lighter weight :)

**Comment by nikkolasg** [comment]
re-org of the codebase to better separate the control plane and and all, for sure.
