### ISSUE TITLE
Measurement of group health

### ISSUE THREAD

**Issue by willscott** [drand/drand#253]
Ideally, a group participant can learn about the current health of the group. In particular:
* which group members have missed publishing their shares for the current round
* how close to the deadline / how much latency is associated with each member
* how many connections / how much bandwidth is each group member recording
* (maybe) which other members is each member directly connected with

**Comment by nikkolasg** [comment]
(just an idea) We could create a binary that is a "drand network health monitoring system", similar to https://metrics.torproject.org/ - drand nodes would regularly report their info on this system and it'd have a dashboard or stg. This dashboard FWIW could even be public, to engage more with the public.

**Comment by willscott** [comment]
When possible, whitebox monitoring is generally preferable.
(in the form of "nodes export a handler where they publish metrics.")
this would be like the basic example in https://prometheus.io/docs/guides/go-application/

Then prometheus can automatically pull from all the group members and will take care of all of the time series recording / analysis logic so we don't have to write anything custom.

**Comment by nikkolasg** [comment]
(1) drand already support a `prometheus` server as well as `pprof` (@ltv511 brought that code here :) Have a look in `metrics/` !
(2) I understand how (1) can give information about information about our own node, but you want that to be publicly reachable from other nodes as well ?  I am not sure I understand.

**Comment by willscott** [comment]
awesome 👍 i would advocate having the metrics/ endpoint be made available at the same endpoint as the within-group (e.g. grpc) communication channel.
Each participant is invested in the other group members being stable / healthy, and should be able to run a prometheus instance polling all the others if that's a useful way for them to get that information.

**Comment by nikkolasg** [comment]
Oh I see. Isn't that complicated though ? You'd need to make protobuf packets that contain all information that prometheus is able to export and import that into prometheus on the receiving side, not speaking about updatability... ?  Or am I missing stg ? 
It seems prometheus can already scrape remote nodes, so isn't that simpler to just open another port and let prometheus does it job alone, scraping data from all the other nodes ?

Also, orthogonal to the exact way of doing this, I still think it would be nice to be able to have some kind of public health check dashboard. Obviously first step is to allow "us" developpers to log into a potential grafana webpage exported by prometheus, but being able to have a publicly reachable webpage as well seems like a good (potentially long term) goal to me.

**Comment by willscott** [comment]
once we've got a grafana that looks good, making a read-only view of it available publicly should be easy.

I'd be happy to see the additional port agreed to be forwarded by group members as we figure out what connectivity looks like.

Or we could use your existing multiplexer between HTTP and GRPC to have it be an HTTP endpoint on the port. Agree that it isn't worth the complexity of serializing to protobuf

**Comment by nikkolasg** [comment]
> I'd be happy to see the additional port agreed to be forwarded by group members as we figure out what connectivity looks like.

I see that's a good point; maybe it's worth exploring a push based mechanism then  https://prometheus.io/docs/instrumenting/pushing/, where we and potentially other would maintain this global prometheus health system checking server ?

**Comment by willscott** [comment]
but then we need to coordinate how you get the remote parties to add / remove / change the monitoring URLs they're pushing to.
If we can agree to keep the handler open, it makes reconfiguration subsequently much easier

**Comment by nikkolasg** [comment]
> but then we need to coordinate how you get the remote parties to add / remove / change the monitoring URLs they're pushing to.
It's never gonna be black and white when networking is concerned xD For this, having versions and multiple enpoints would be ok guess ?, as it's done in other systems (like bootstrapper nodes, or forks in blockchains etc). My general worry is that opening a port and receiving packet is always more problematic than just sending a packet out - 

But I also like the idea of using the multiplexing to binds prometheus to the same port :D Hopefully it doesn't use gRPC though. There's a few metrics that are using this technique already [here](https://github.com/drand/drand/blob/master/net/listener_grpc.go#L249)

**Comment by hsanjuan** [comment]
Note that we will likely be running telegraf and exporting to a 3rd-party provided influxdb endpoint (like lotus does now). I am against running any additional metric-collection infra ourselves in the short term because other people do it very well. Telegraph is able to scrape prometheus endpoints though. Influx is then a source for graphana.

I would let every drand peer export whatever data seems useful (i.e. number of peers that participated in the last round).

**Comment by willscott** [comment]
Sounds good. I don't think I have any strong preference about collection pipeline beside that it will be good if one exists.
If we've already got one, lets use it. we can limit the work we do here to making sure nodes export a sane /metrics handler with relevant data to track.

**Comment by willscott** [comment]
metrics are now shared between group members, i believe addressing this issue
