### ISSUE TITLE
Simplify startup

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#260]
I would like drand to:

* Have a configuration file with the necessary information for that peer: if it's a leader, how to run the setup phase if it was not run before, or potentially how to run reshare if we changed the config.
* Starting drand should just start sharing: if it's a leader and no setup phase was run, then run it. Potentially run reshare phases if we changed options. Otherwise, just connect to the leader and start working.

Wish: Drand nodes can have a list of where to contact the leader, but other than that they should be able to run on any IP address that is randomly given to them and change it at any time. It appears that somehow this is linked to a fixed hostname or to fixed ip address.

Since they contact the leader first, they can learn about the current addresses of others from that peer (they could do that by connecting to other nodes).

The ultimate goal is that, by providing the right configuration pieces, we can `drand start` a cluster of peers without any further manual intervention, even if they had never been started before or if the settings have changed (i.e. the threshold).

**Comment by willscott** [comment]
this seems doable :+1:
