### ISSUE TITLE
Make the demo / test-integration works on MacOS

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#261]
The demo creates peers at addresses `127.0.0.1:<random_port>`, `127.0.0.2:<random_port>` , `127.0.0.3:<random_port>`  ... For ease of debugging, you directly know which folder (`/tmp/drand-full/node{1,2,3...}`) to look into for the logs when you see the address on the output of the demo.
Unfortunately it seems MacOS seems to not allow to create localhost addresses different than `127.0.0.1`.
Simple fix is to make the daemon listens on `127.0.0.1:<randomport>` - the public address is still the same but the daemon listens on a "regular" address.

**Comment by willscott** [comment]
fixed by #263, right?
