### ISSUE TITLE
Separate HTTP API and make it optional with a flag

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#268]
We want to make the HTTP API exposed on another port, optional with a `--http-api <address>` flag.

**Comment by willscott** [comment]
we should figure out where the metrics reporting falls out when we do this.

De-muxing the main GRPC port seems good from a simplicity / auditability / minimal surprise perspective. That'll mean we should expect to expose an additional 'metrics' port as well, and should make sure it gets exposed.
