### ISSUE TITLE
Master branch protection rules

### ISSUE THREAD

**Issue by alanshaw** [drand/drand#275]
Master branch protection rules -> the changes I'm planning to make here are:

1. "Require status checks to pass before merging" (`ci/circleci: build`). Tests should ALWAYS be passing before merging into master.
1. "Include administrators", since I don't believe admins need a daily temptation to merge without review and since they're admins, and they absolutely _have_ to do this, then they can always change the setting temporarily.

Please can I get a 👍 or a comment with feedback/suggestions?

---

Current settings:

![Screenshot 2020-05-08 at 10 35 12](https://user-images.githubusercontent.com/152863/81393236-ec1fbe00-9117-11ea-9223-e19815c00936.png)

**Comment by daviddias** [comment]
Approved ✅

**Comment by jsoares** [comment]
It's worth noting that master is not currently passing CI checks -- might want to fix that first or even non-code commits (e.g. https://github.com/drand/drand/pull/259) will be blocked.

**Comment by willscott** [comment]
i'm generally okay with this. i will note that @nikkolasg spent most of yesterday trying to stabilize the integration test and i wouldn't block on that. blocking on build success is very reasonable, and unit tests have been stable enough that i wouldn't object to those becoming required either.

**Comment by alanshaw** [comment]
Closing this as I've applied the updated rules.
