### ISSUE TITLE
non-painful way to merge PRs from forks

### ISSUE THREAD

**Issue by willscott** [drand/drand#339]
To get #337 to build in CI, I had to add the fork as a remote locally, push it to a branch in this repo, and then make an additional PR against the local branch in order to trigger CI. There should be some way for us to trigger CI against the fork in a less painful way, ideally. maybe a bot to automate pulling the branch locally?

**Comment by Kubuxu** [comment]
Someone with admin access has to enable building for forks in CircleCI settings.

**Comment by willscott** [comment]
right now, the Circle settings include a docker secret that iirc is injected into all of the workflows. we'll need to make sure that only gets into the deploy ones before enabling forks

**Comment by willscott** [comment]
mitigated by supplementing with non-privileged github actions workflows that validate both building and linting (though not yet tests passing)

**Comment by Kubuxu** [comment]
CircleCI has option to disable secrets from fork builds. Wouldn't that be enough?

**Comment by willscott** [comment]
Turned that on. :+1:
