### ISSUE TITLE
Latency-Optimized CDN Client

### ISSUE THREAD

**Issue by willscott** [drand/drand#364]
In addition to the current prioritizing client, we should have a module that does non-critical path pulls from other CDNs to estimate latency across all available ones. This is useful for prioritizing the best CDN, and knowing how many backups are available.

**Comment by willscott** [comment]
@alanshaw , the optimizing client now achieves this, I believe

**Comment by alanshaw** [comment]
yerp, and for completeness, this is the PR where it happened: https://github.com/drand/drand/pull/512
