### ISSUE TITLE
read /dist_public.toml: is a directory TEST <verify signature?>: FAILURE

### ISSUE THREAD

**Issue by mrWhiteCrow** [drand/drand#37]
When i try to run the script **run_local.sh** with more than 11 nodes I receive this error 

> message:read /dist_public.toml: is a directory TEST <verify signature?>: FAILURE

 after the terminal show the message: 

>  Starting the leader of the dkg

how can i test the program with more than 10 nodes?

**Comment by nikkolasg** [comment]
Yeah it's a stupid bash program that makes the tests so far and thus only assigns IP address like `2$i` where `i` is a counter that goes from `1 -> 6`. 
To test with more than 10 nodes, you need to r
+ replace every IP as above, with stg like `expr 20 + $i`.
+ change a `n` variable at the top of the script to your number

If you do those changes, I'd greatly appreciate if you could submit a PR for that, that'd be really neat. This bash script is getting way larger than expected and it either needs some love like this kind of change, or a complete rewrite in a more solid language.

**Comment by nikkolasg** [comment]
Closing since outdated. Run the `make demo` command to play with a local network.
