### ISSUE TITLE
Round 1 doesn't display correctly

### ISSUE THREAD

**Issue by ltv511** [drand/drand#372]
The first round is not returned correctly by the server. For example, https://drand.cloudflare.com/public/1  hangs but https://drand.cloudflare.com/public/2 successfully returns the round.

Perhaps because the first round has no previous_signature?

**Comment by hsanjuan** [comment]
I confirm this. Only happens with the http api exposed by the drand node, not with the http relay though.

**Comment by willscott** [comment]
Should be fixed as a side cleanup in #377

**Comment by willscott** [comment]
root cause fixed in #393
