### ISSUE TITLE
HTTP Relay: some issues with responses

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#378]
The content-type should probably be set to json in all endpoints. /latest returns text/plain, /round returns application/json, /group returns text/plain.

The max-age and expire headers are set to 1 week for the /round endpoints, which are immutable. I am not sure if we would like to increase this to 1 year or something, but it's probably enough this way (in case we change anything in the response format).

The /group endpoint has a 1 Week expiration set, we should probably shorten that in case we change the group (to 1 hour?).

**Comment by willscott** [comment]
i believe you're on an older version? all 3 endpoints should return application/json on the network kuba & i are running, but do not on dev1.drand.sh

I don't think we expect the subset of the information that'll be shown on group to be mutable (it should be the key & period information, not affected by participants / resharings) so i think long lived expiration should be okay.

**Comment by hsanjuan** [comment]
we should include a version header. I'm sure that the I'm hitting are on the latest master... when queried directly they output text/plain. I manually installed master just in case.

**Comment by hsanjuan** [comment]
that is, with `curl -v 127.0.0.1:relay-port/public/24113`

**Comment by willscott** [comment]
see #394 - preference for header vs endpoint?

**Comment by willscott** [comment]
i believe the issues scoped in this issue are resolved.
