### ISSUE TITLE
HTTP: Not found for inexistent rounds

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#382]
I think we are returning 500 when a round does not yet exist? Should probably use 404 ? Or 400?

**Comment by alanshaw** [comment]
404 👍

**Comment by willscott** [comment]
<img width="388" alt="Screen Shot 2020-05-22 at 8 35 21 AM" src="https://user-images.githubusercontent.com/428199/82684313-3a988680-9c07-11ea-871b-1ea2d30d72ad.png">

**Comment by hsanjuan** [comment]
ack, must have been due to misconfig or cached errors.
