### ISSUE TITLE
Pubsub relay: add subcommand to generate/show identity

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#401]
In order to satisfy the ability to easily deploy pubsub relays I would like:

* A `./relay-pubsub init` subcommand that generates the identity
* A `./relay-pubsub id` command that prints the peer ID
* I would like the identity stored in base64 and not binary
* Bonus: use `~/.relay-pusub` or similar to store the stuff, make sure folders are created when they do not exist during `init` and add a flag to override location.

**Comment by alanshaw** [comment]
For peer ID you can use `./relay-pubsub peerid`. It'll actually load _or_ create the key (you can pass `--identity` to specify the file). Is that good enough for 1 & 2?

There's a `--store` option coming in https://github.com/drand/drand/pull/357/files#diff-253ccd93a05f1f9a292a9855ef83b86cR59-R63

I can probably send a PR to store the identity as base64...😘

**Comment by hsanjuan** [comment]
I realized I wrote `relay-pubsub` instead of  `relay-gossip` ?

And I don't see such option ?

**Comment by Kubuxu** [comment]
I wrote the command and didn't plug it it. https://github.com/drand/drand/pull/407
