### ISSUE TITLE
CLI tools --version should show the version

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#456]
Even though we set gitCommit, version etc, --version returns 0.0.1. Tested for relay gossip, should look into the others too.

```
[hector@relay-gossip0 ~]$ relay-gossip --version
beacon-relay version 0.0.1
```

**Comment by willscott** [comment]
what context are you building the relay-gossip binary in?

as with https://github.com/drand/drand/blob/master/Dockerfile#L35 we're going to have to set the variables specific to the binary
