### ISSUE TITLE
Handle duplicated packets during DKG

### ISSUE THREAD

**Issue by willscott** [drand/drand#559]
ensure that receiving a `DealBundle`, `ResponseBundle`, or `JustificationBundle` is idempotent.
Ensure also that receiving multiple deals / responses / justifications from the same index that are both valid results in an error and backing out of a resharing.

per this interface:
https://github.com/drand/kyber/blob/master/share/dkg/protocol.go#L18

**Comment by nikkolasg** [comment]
This is already the case at the kyber level with the use of a [`set`](https://github.com/drand/kyber/blob/master/share/dkg/protocol.go#L372) that contains the logic
