### ISSUE TITLE
new members joining a group can fetch group.toml from leader automatically

### ISSUE THREAD

**Issue by willscott** [drand/drand#623]
currently, a node to be included needs to specify `--from` to provide a group.toml for the group they want to reshare into.
Instead, they should be able to automatically fetch this from the reshare leader.

**Comment by nikkolasg** [comment]
Yep that sounds like a good idea - since we already trust the leader. We should make sure that the Nonce in the DKG depends both on the previous and new group btw this is not the case. Such that in case a new member got an invalid group, he'll not be able to participate.
