### ISSUE TITLE
Node can end up in the group despite not having received a share

### ISSUE THREAD

**Issue by jsoares** [drand/drand#714]
In a previous ceremony, some nodes were unable to receive shares (`setup_reshare="failed to receive dkg info" err="context canceled"`) yet still ended up in the group file. 

This created an inconsistent state in which nodes cannot participate because they lack a share but also cannot join because they're already in the group (`setup_reshare="failed to run resharing" err="control: can't reshare without a share"`).

Per @nikkolasg, this shouldn't be possible: nodes should only be added to the group after having received a share.

**Comment by nikkolasg** [comment]
I think this PR solved this issue https://github.com/drand/drand/pull/752

**Comment by CluEleSsUK** [comment]
Other than dedis not getting a share due to filesystem permissions, we haven't seen this in any recent ceremonies, so closing.
