### ISSUE TITLE
investigate non c-go builds

### ISSUE THREAD

**Issue by willscott** [drand/drand#736]
github.com/DataDog/zstd is in the dependency tree and includes cgo code. would be great if the go binary didn't need this (likely related to standard web server stuff, but not entirely clear)

**Comment by willscott** [comment]
It appears that compilation should succeed with `CGO_ENABLED=0` - see https://github.com/dgraph-io/badger/issues/1104

**Comment by AnomalRoil** [comment]
Confirmed working now, `zstd` is also no longer in the dep treee
