### ISSUE TITLE
fetch public "no such file or directory"

### ISSUE THREAD

**Issue by jeffallen** [drand/drand#75]
```
$ ./drand-000e5e56 f public dedis.nella.org:8890
open : no such file or directory
```

This seems to be because it expects a -p argument, but it is also unclear what I'm supposed to use as the -p argument.

**Comment by gabbifish** [comment]
The -p argument is supposed to be the distributed key file (from `drand fetch dist_key <addr>:<port>`). The readme definitely needs to get updated, though.

**Comment by nikkolasg** [comment]
readme is updated with latest instruction.
