### ISSUE TITLE
How to create a random number from "randomness"

### ISSUE THREAD

**Issue by jjmerri** [drand/drand#751]
Sorry, I couldn't find a better place to ask this. How can I create a random integer from "randomness" that is returned from the /public/latest endpoint? I'm trying to do this in Java and I was thinking I could convert it to an integer and seed the random number generator but randomness is too big to convert to long.

example response from the endpoint
`{
"round": 156125,
"randomness": "17270f62a457e3d43afda939ca05dac3b4a4ca396baf7a8750d1acc727916fbc",
"signature": "aef268f51d162ac12406fd677b2ac1b78ab6c3280a75deeb1e3dd22951bec24c06e99ea5bd4fcf7a2aca05fb18e13e7c08a2a327402609b3860b3416d46518af64c3a003dbcc19db24d130ddddd7c5e2048e8dc437c986da2880b927fcc6276c",
"previous_signature": "955ea24448e407a420bbb5a65303b383ba100ac54d629654244072f487cf9699b1d2aeaaa2acf59a06d25e20a31cc6200916d112f1550a49cd49a92dc318f4778524cf6ed1acbac680e6d2c521b2fa15f8d0369ea201933a15e6e4598356fa51"
}`

**Comment by willscott** [comment]
all bytes will be uniformly random. you can safely slice off however many you need and use that subset.

```java
import org.apache.commons.codec.binary.Hex;

byte[] decoded = Hex.decodeHex("...");
byte[] slice = Arrays.copyOfRange(decoded, 0, 8);
BigInteger n = new BigInteger(slice);
n.longValue();
```

**Comment by jjmerri** [comment]
Thanks for the response @willscott! I'm not super familiar with SHA hashes but given that "randomness" is the SHA-256 hash of "signature" should I just use "signature" instead of "randomness" or would both be uniformly random?

**Comment by willscott** [comment]
you should use randomness (the after-hashing bytes). signature is not uniformly random.
