### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by nikkolasg** [drand/drand#76]
The logging in drand is very basic. We need to extend it to something more standardized, with dates and general format.

**Comment by PizzaWhisperer** [comment]
What do you think about simply get rid of the json formatting and add a timestamp ? i.e. 
```
timestamp: 2018-11-17 16:58:47.581791682 +0100 CET
index: 2582
randomness: ae56dd593edfc66746bb4f7c90f51dab7c1b27dabaed32096bbfc8b7d6f60884
verification: ok
```
for a get public ?

**Comment by nikkolasg** [comment]
Well I'm talking more about the *daemon side* logging rather than the *client side*'s outputs . Clients have their *output* of the command (different than logs) in JSON as they should be able to use it for post processing. If clients have verbosity on, then logs appear and there it should be probably the same as the daemon.

I was more thinking of something in the veins of what web servers are outputting:
```
<time> <module> <ip if possible>: <message>
```
But we should check of standard tools are doing it and expecting logs, i.e. syslog for example. If drand could output standard logs, then these logs could be consumed by monitoring processes, dashboards etc, fairly easily.

**Comment by nikkolasg** [comment]
Logging is using a structured logging now. Closing for now.
