### ISSUE TITLE
resharing

### ISSUE THREAD

**Issue by mingkaiyang** [drand/drand#764]
I don't understand the Resharing phase.Without changing the public key,How is it able to change the threshold and the number of nodes. I watched some videos,but I still don't understand .And I don't understand the code by GO.So please help me understand this phase  in plain language or pictures.Thank you

**Comment by mingkaiyang** [comment]
Is there any article on how to reshare, please give me a link

**Comment by willscott** [comment]
Resharing is based on the cryptographic properties on the multi-party computation that is used to shard the shares of the private key across group participants.

The underlying academic paper https://ieeexplore.ieee.org/abstract/document/7958592 is perhaps the most useful place to understand the algorithm.
