### ISSUE TITLE
Startup with a large existing beacon history can be slow

### ISSUE THREAD

**Issue by willscott** [drand/drand#765]
Members of the current league of entropy report that restarting the drand daemon can take 7-9 minutes.
This may mean that all previous beacons are being re-validated on startup. We should potentially be lazy about doing that or otherwise figure out why startup is that slow.

**Comment by nikkolasg** [comment]
> This may mean that all previous beacons are being re-validated on startup.
drand is not revalidating the whole chain at startup, it simply loads the last beacon saved and checks if it must catchup or not. Drand assumes every beacon saved in the database is correct and correctly linked.

**Comment by AnomalRoil** [comment]
Then the slow startup is strange. We might want to do some profiling on the testnet.

**Comment by nikkolasg** [comment]
Mhhh We have a line [`baseLen += bucket.Stats().KeyN`](https://github.com/drand/drand/blob/v1.1.1/chain/boltdb/store.go) that is called during initialization. On boltdb `Stats()` seems to be a big for loop `forEachPage` - it could be that looping over all pages takes long time now.
