### ISSUE TITLE
Expose group size and threshold via prometheus metrics

### ISSUE THREAD

**Issue by lukevalenta** [drand/drand#767]
We (Cloudflare) currently have alerts set up to trigger when the group_connections metric falls below the number of nodes in the current drand group, but that alert has to be manually adjusted after every resharing. Instead, we should expose the current size and threshold of the group as separate prometheus metrics.

**Comment by willscott** [comment]
@hsanjuan  notes that `group_connections` is not correct at the moment, and believes that it may not always decrement properly when connections drop. We should also confirm that metric is reporting correctly before relying on it.
