### ISSUE TITLE
Panic in boltdb

### ISSUE THREAD

**Issue by lukevalenta** [drand/drand#770]
I got the following panic message in Cloudflare's internal staging drand network after restarting the nodes with v1.2.1 (commit 44b55ad2). On the surface it appears to be due to some corruption in the boltdb database, but manually examining the boltdb file with boltbrowser I wasn't able to find any corruption.

It's entirely possible that this bug is specific to Cloudflare's setup, but just wanted to file it here in case it crops up elsewhere. 
Each node runs in a kubernetes container which loads the drand database from an S3 bucket when the node is started, and saves to the bucket when the node is stopped, so perhaps this is where the corruption was introduced.

I resolved the issue in the internal network by just restarting the network with a new database, but obviously that won't work for the testnet or mainnet.

```
drand: will already start running randomness beacon
Folder different permission: 0755 vs 0740 
level=info ts="Wed, 11 Nov 2020 13:24:00 UTC" call=drand.go:145 private_listen=0.0.0.0:8083 control_port=8883 public_listen=0.0.0.0:4433 folder=/root/.drand
Folder different permission: 0755 vs 0740 
level=debug ts="Wed, 11 Nov 2020 13:24:01 UTC" call=cli.go:260 serving=localhost:8083
	/work/cmd/drand/vendor/go.etcd.io/bbolt/node.go:376 +0x6a5
go.etcd.io/bbolt.(*node).spill(0xc0001dc7e0, 0xc0003be0e0, 0x1)
 
panic: pgid (21069) above high water mark (21069)
goroutine 1 [running]:
	/work/cmd/drand/vendor/go.etcd.io/bbolt/node.go:351 +0xba
go.etcd.io/bbolt.(*node).spill(0xc0001dc770, 0xc00029c6f0, 0xc0001e75c0)
go.etcd.io/bbolt.(*DB).Update(0xc0002ec600, 0xc0001e79c0, 0x0, 0x0)
	/work/cmd/drand/vendor/go.etcd.io/bbolt/bucket.go:537 +0x3d5
	/work/cmd/drand/vendor/go.etcd.io/bbolt/db.go:701 +0xf6
	/work/cmd/drand/vendor/go.etcd.io/bbolt/bucket.go:570 +0x473
	/work/cmd/drand/vendor/go.etcd.io/bbolt/tx.go:161 +0xec
go.etcd.io/bbolt.(*Tx).Commit(0xc0003f48c0, 0x0, 0x0)
go.etcd.io/bbolt.(*Bucket).spill(0xc0003f48d8, 0x59f27323, 0x1461b80)
go.etcd.io/bbolt.(*Bucket).spill(0xc000295480, 0xc00029c600, 0xc0001e77b8)
	/work/cmd/drand/chain/boltdb/store.go:73 +0x57
github.com/drand/drand/chain/boltdb.(*boltStore).Put(0xc0003a7f60, 0xc000295440, 0xc00029c630, 0x966aab)
	/work/cmd/drand/chain/beacon/node.go:69 +0x170
github.com/drand/drand/chain/beacon.NewHandler(0xe84680, 0xc000294d40, 0xe87080, 0xc0003a7f60, 0xc00029c600, 0xe845c0, 0xc0001db400, 0x6, 0x20, 0xc0003a7e40)
	/work/cmd/drand/core/drand.go:331 +0x1d2
	/work/cmd/drand/core/drand.go:221 +0x2f
github.com/drand/drand/core.(*Drand).newBeacon(0xc00018c300, 0x0, 0x0, 0x0)
	/work/cmd/drand/vendor/github.com/urfave/cli/v2/app.go:306 +0x814
github.com/urfave/cli/v2.(*App).RunContext(0xc000210000, 0xe7e880, 0xc000040038, 0xc000032120, 0x11, 0x12, 0x0, 0x0)
github.com/urfave/cli/v2.(*Command).Run(0x1451480, 0xc00007dac0, 0x0, 0x0)
	/work/cmd/drand/cmd/drand-cli/cli.go:260 +0x144
github.com/drand/drand/cmd/drand-cli.glob..func1(0xc00007df40, 0xf, 0x1c)
	/work/cmd/drand/cmd/drand-cli/daemon.go:39 +0x482
	/work/cmd/drand/vendor/github.com/urfave/cli/v2/app.go:215
github.com/drand/drand/cmd/drand-cli.startCmd(0xc00007df40, 0xc000010018, 0xd680c1)
github.com/urfave/cli/v2.(*App).Run(...)
	/work/cmd/drand/main.go:12 +0x67
main.main()
github.com/drand/drand/core.(*Drand).StartBeacon(0xc00018c300, 0xc00010a101)
	/work/cmd/drand/vendor/github.com/urfave/cli/v2/command.go:164 +0x4e0
```

**Comment by nikkolasg** [comment]
On [etcd/boltdb page](https://github.com/etcd-io/bbolt), we can see the following limitations:

> The data structures in the Bolt database are memory mapped so the data file will be endian specific. This means that you cannot copy a Bolt file from a little endian machine to a big endian machine and have it work. For most users this is not a concern since most modern CPUs are little endian.

> Because of the way pages are laid out on disk, Bolt cannot truncate data files and return free pages back to the disk. Instead, Bolt maintains a free list of unused pages within its data file. These free pages can be reused by later transactions. This works well for many use cases as databases generally tend to grow. However, it's important to note that deleting large chunks of data will not allow you to reclaim that space on disk.

Did you stop the node gracefully or by killing the process ? 
Any chance that one of the two limitations above might have kicked in (i dont think for the first one but we never know!) ?

**Comment by lukevalenta** [comment]
We currently killi the process when restarting a node--should we be running `drand stop` instead? The save to S3 actually happens as a kubernetes `preStop` command, so runs before the drand process is killed, so it's possible that the file got copied while the node was halfway through writing to it.

**Comment by willscott** [comment]
Cleanly drand stop should help prevent corruption

**Comment by lukevalenta** [comment]
Sounds good. Is there any reason why we shouldn't catch the termination signal and clean up though?

**Comment by nikkolasg** [comment]
No particular reason except we haven't done this yet ! Tracked in https://github.com/drand/drand/issues/773

**Comment by lukevalenta** [comment]
I'll close this issue as it doesn't seem related to drand itself, and is more of an issue of how we're handling the db in our setup.
