### ISSUE TITLE
Error: unexpected HTTP status 404 for URL https://drand.cloudflare.com/public/339321

### ISSUE THREAD

**Issue by mh3663** [drand/drand#774]
Instead of regularly updating hex strings, the drand.love page reports…

        An error occurred loading the latest randomness:
        Error: unexpected HTTP status 404 for URL https://drand.cloudflare.com/public/339321

**Comment by lukevalenta** [comment]
What could have happened is that the drand server returned a 404 when a future round was requested, and then Cloudflare cached the 404 response for a few minutes (https://community.cloudflare.com/t/cache-everything-and-dont-cache-404-at-all/108912).

Looks like we aren't setting cache control headers for 404 messages https://github.com/drand/drand/blob/master/http/server.go#L257

@hsanjuan @willscott @nikkolasg

**Comment by willscott** [comment]
Good catch, @lukevalenta  - do you have a sense of if it would be preferable to set the header as `Cache-Control: no-cache` or to set it with the number of seconds until the round is predicted to become available?
My worry is if we say "cache for 15 seconds", the CDN layers may stiil impose their own minimum of 5 minutes or similar. A more explicit "no-cache" seems safer to avoid caching, but incurs more load back to the drand http app.

**Comment by lukevalenta** [comment]
I think caching until the round is predicted to be available makes the most sense, since otherwise it's potentially a DoS vector. At least for Cloudflare that should fix the issue since the CDN is set up to respect the origin cache rules (and applies defaults if the cache headers aren't specified).
