### ISSUE TITLE
Multibeacon migration should delete or rename original config files

### ISSUE THREAD

**Issue by hsanjuan** [drand/drand#854]
I found it confusing that the group file and drand.db and keys etc. that are used are now inside `multibeacon/default`, but the original files are still in place, and potentially unused.

This might cause confusion or bad mistakes for operators (i.e. backing up the wrong things).

**Comment by willscott** [comment]
this was on purpose to allow the possibility to downgrade

**Comment by willscott** [comment]
Yes, i think this is a reasonable state for now.
We can file an issue that we should clean up the old ones in the next (e.g. v1.5 release branch) once all networks are updated to multibeacon.
