### ISSUE TITLE
go get causes error from github.com/drand/kyber-bls12381

### ISSUE THREAD

**Issue by advanderveer** [drand/drand#915]
When I run `go get github.com/drand/drand` (as instructed in the documentation) I get: 
```
go/pkg/mod/github.com/drand/kyber-bls12381@v0.2.1/kyber_g1.go:92:50: cannot use &s.(*mod.Int).V (type *big.Int) as type *bls12381.Fr in argument to bls12381.NewG1().MulScalar
go/pkg/mod/github.com/drand/kyber-bls12381@v0.2.1/kyber_g2.go:97:50: cannot use &s.(*mod.Int).V (type *big.Int) as type *bls12381.Fr in argument to bls12381.NewG2().MulScalar
```

I'm using a m1 Mac with go 1.17. 

EDIT: I've tried it on amd64 linux machine running go get in the same repo and it seems to work. So strange, maybe some architecture build flag is triggering the above error?

**Comment by nikkolasg** [comment]
Sorry for the delay - I haven't tested on a M1 but there are many things that break on M1 so .. compatibility will come from Golang I guess but on our side, we only guarantee compilation on Linux platforms...

**Comment by nikkolasg** [comment]
Thanks for reporting & let us know if you find out more info. I'll close the issue in the meantime.

**Comment by advanderveer** [comment]
Thank you for the response, too bad but understandable.

**Comment by nikkolasg** [comment]
You could try reporting the issue here https://github.com/kilic/bls12-381 this is the underlying crypto library that drand uses and it has many compilation flags. If the author upstream a patch for M1, we'll take it.
