### ISSUE TITLE
"drand get private" does not say who it contacted

### ISSUE THREAD

**Issue by jeffallen** [drand/drand#93]
It takes the --nodes whitespace separated list. And also a group file to know the public keys of the nodes.

It returns:

```
{
    "Randomness": "d15e24aa8b0f1c20df0ef5e005c4b607f9448d420d550a1fb6e3bd768640b1ab"
}
```

I think there should be a "Node" in there, to tell me which server it ended up getting data from.

And I'd like, if --nodes is empty, that it defaults to all nodes in the group file.

And I'd like that items from --nodes are tried in a random permutation order.

With all those changes, then repeated calls to "drand get private" will talk to all the servers in the network.

Another possibility: an -all option, that causes each of the servers in the --nodes option to be tried. Then I can use "drand get private --all" to try talking to each of the servers and see which ones work.

**Comment by AnomalRoil** [comment]
Drand is really about public distributed randomness, so we are not supporting private randomness anymore, I'm afraid.
