### ISSUE TITLE
Tests are wrongly using require.NoError from goroutines

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#957]
It is not supported by testing's `FailNow()` to be called from goroutines, as per the doc:

>  FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test. Calling FailNow does not stop those other goroutines. 

And `require.NoError` calls `FailNow`.

This typically means that e.g. if any of these `require.NoError` fail, then the whole test would still keep running instead of failing and will be stuck for hours in a deadlock waiting on "wg.Wait()":
https://github.com/drand/drand/blob/19ba7479f0ab0799bdf1b30bc7551a9cae2fc385/core/util_test.go#L295-L308

**Comment by Bexanderthebex** [comment]
Just trying to understand why we need to have go routines in here. I am new to the repo and want to familiarize myself so I would appreciate your patience if this comes off as a dumb question

**Comment by CluEleSsUK** [comment]
Not a problem @Bexanderthebex ! The `InitDKG` function triggers a long running process where nodes do some secret sharing and organise the new layout of the network.
We want to trigger this in parallel so all the nodes can do the necessary work before continuing on with the test.

**Comment by Bexanderthebex** [comment]
@CluEleSsUK got it, I opened a PR to fix this https://github.com/drand/drand/pull/1076
