### ISSUE TITLE
Need to upgrade our dependencies

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#961]
This will cause some refactor because if we want to support Go 1.18, we need to have a version >v0.17.0 of [go-libp2p-quic-transport](https://github.com/libp2p/go-libp2p-quic-transport) since it's the one merging quic-go in a version >v0.26.0 that is compiling with Go 1.18, but this means upgrading to a version of go-libp2p larger than v0.18.0, but this version had a lot of changes:
- https://github.com/libp2p/go-libp2p/releases/tag/v0.18.0

So we'll need to upgrade our dependencies, but that's going to take some time and fiddling.

**Comment by CluEleSsUK** [comment]
Done
