### ISSUE TITLE
Running a resharing directly after the intial DKG fails with unclear error message

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#968]
Currently, running a resharing directly after having run the initial DKG as in this script: 
https://github.com/drand/drand/blob/master/test/local.sh

But with a `sleep 30` instead of `sleep 60` on line 59 as in there: 
https://github.com/drand/drand/blob/c7980b49610baebbe31dce6623e867fdb212578b/test/local.sh#L59
will fail upon resharing with the error:
```
error setting up the network: rpc error: code = Unknown desc = control: genesis time is in the future
```

This seems to be normal and caused by the fact that after a DKG the Genesis time is set some time in the future. 

Todo: 
- either have a clearer error message saying we need to issue at least one beacon with the initial shares maybe?
- or change it all so that we can run a resharing even if we haven't started the chain yet. This might be the best.

**Comment by CluEleSsUK** [comment]
this error no longer exists (...though I don't know why - it seems like a reasonable error tbh)
