### ISSUE TITLE
Remove deprecated "info_hash" field in protobuf

### ISSUE THREAD

**Issue by AnomalRoil** [drand/drand#985]
This will be made useless after #984 is merged.
https://github.com/drand/drand/blob/07f364481b491f2f05fb5370068f16648fc0a647/protobuf/drand/control.proto#L258-L260

Sadly removing it makes it non-backward compatible, so we have to keep it around for now.

Todo: remove this in our next Major/Minor release.

**Comment by CluEleSsUK** [comment]
Doesn't seem to exist anymore
